#!/bin/bash
# ============================================================================
# DEPLOY SCRIPT
# ============================================================================
# Purpose: Push changes to GitHub and deploy to Home Assistant
# Generated by: hass-gen init (customize as needed)
# ============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION - Edit these for your setup
# ─────────────────────────────────────────────────────────────────────────────

PI_HOST="root@homeassistant.local"  # SSH host for your HA instance
PI_SCRIPT="/root/deploy.sh"          # Remote script to run after push

# ─────────────────────────────────────────────────────────────────────────────
# COLORS
# ─────────────────────────────────────────────────────────────────────────────

WHITE='\033[1;37m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
DIM='\033[2m'
NC='\033[0m'

SPINNER='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'

# ─────────────────────────────────────────────────────────────────────────────
# CHECKS
# ─────────────────────────────────────────────────────────────────────────────

BRANCH=$(git branch --show-current)

if [ "$BRANCH" = "main" ]; then
    echo -e "${RED}Error: Switch to a feature branch first.${NC}"
    exit 1
fi

UNPUSHED=$(git log origin/$BRANCH..$BRANCH --oneline 2>/dev/null | wc -l | tr -d ' ')
if [ "$UNPUSHED" -eq 0 ]; then
    echo -e "${YELLOW}No new commits to deploy on $BRANCH${NC}"
    echo -e "${DIM}Make changes and commit before deploying.${NC}"
    exit 0
fi

# ─────────────────────────────────────────────────────────────────────────────
# PUSH TO ORIGIN
# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${WHITE}📤 Pushing $BRANCH to origin...${NC}"
git push origin "$BRANCH" 2>&1 | sed "s/^/   /"

# ─────────────────────────────────────────────────────────────────────────────
# DEPLOY TO PI
# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${CYAN}🍓 Deploying to Pi...${NC}"
echo ""

TEMP_OUT=$(mktemp)
TOTAL_START=$SECONDS

ssh "$PI_HOST" "$PI_SCRIPT $BRANCH" > "$TEMP_OUT" 2>&1 &
SSH_PID=$!

spin_until_stage() {
    local msg="$1"
    local stage_marker="$2"
    local start=$SECONDS
    local i=0
    
    while kill -0 $SSH_PID 2>/dev/null; do
        if grep -q "$stage_marker" "$TEMP_OUT" 2>/dev/null; then
            local elapsed=$((SECONDS - start))
            printf "\r   ${GREEN}✓${NC} ${msg} ${DIM}(${elapsed}s)${NC}          \n"
            return 0
        fi
        
        if grep -q "\[STAGE:CHECK_FAIL\]" "$TEMP_OUT" 2>/dev/null; then
            local elapsed=$((SECONDS - start))
            printf "\r   ${RED}✗${NC} Config check failed ${DIM}(${elapsed}s)${NC}          \n"
            return 1
        fi
        
        local elapsed=$((SECONDS - start))
        printf "\r   ${YELLOW}${SPINNER:i++%10:1}${NC} ${msg}... ${DIM}${elapsed}s${NC}  "
        sleep 0.1
    done
    
    if grep -q "$stage_marker" "$TEMP_OUT" 2>/dev/null; then
        local elapsed=$((SECONDS - start))
        printf "\r   ${GREEN}✓${NC} ${msg} ${DIM}(${elapsed}s)${NC}          \n"
        return 0
    fi
    return 1
}

spin_until_stage "Config check" "\[STAGE:CHECK_PASS\]"
CHECK_RESULT=$?

if [ $CHECK_RESULT -eq 0 ]; then
    spin_until_stage "Home Assistant restart" "\[STAGE:RESTART_DONE\]"
fi

wait $SSH_PID
EXIT_CODE=$?

TOTAL_TIME=$((SECONDS - TOTAL_START))

echo ""
echo -e "${DIM}── Pi log ──${NC}"
grep -v "^\[STAGE:" "$TEMP_OUT" | while IFS= read -r line; do
    echo -e "   ${DIM}│${NC} $line"
done
echo -e "${DIM}────────────${NC}"
rm -f "$TEMP_OUT"

if [ "$EXIT_CODE" -eq 0 ]; then
    echo ""
    echo -e "${GREEN}✅ Deploy succeeded!${NC} ${DIM}(${TOTAL_TIME}s total)${NC}"
    
    echo -e "${WHITE}📥 Updating local main...${NC}"
    git fetch origin main:main 2>&1 | sed "s/^/   /"
    
    echo ""
    echo -e "${GREEN}🎉 Done - staying on $BRANCH (main updated)${NC}"
else
    echo ""
    echo -e "${RED}❌ Deploy failed${NC}"
    echo -e "${RED}   Fix the issues and try again.${NC}"
    exit 1
fi

